"""
Event Sourcing schema definitions for Project Capital Vortex.
Defines immutable event structures with validation and type hints.
All events are stored in Firestore with composite indexes for efficient querying.
"""

from datetime import datetime
from typing import Dict, Any, List, Optional, Union
from enum import Enum
from dataclasses import dataclass, asdict, field
from google.cloud.firestore_v1 import SERVER_TIMESTAMP

import logging

logger = logging.getLogger(__name__)


class EventType(str, Enum):
    """Enumeration of all possible event types in the system."""
    MARKET_DATA = "market_data"
    MOMENTUM_SIGNAL = "momentum_signal"
    LIQUIDITY_DECISION = "liquidity_decision"
    TRADE_EXECUTION = "trade_execution"
    POSITION_UPDATE = "position_update"
    STRATEGY_PERFORMANCE = "strategy_performance"
    SYSTEM_HEALTH = "system_health"
    ERROR_EVENT = "error_event"


class AssetType(str, Enum):
    """Supported asset types for trading."""
    MEME_COIN = "meme_coin"
    STABLE_COIN = "stable_coin"
    LIQUIDITY_POSITION = "liquidity_position"


@dataclass
class BaseEvent:
    """Base class for all events with common metadata."""
    event_type: EventType
    timestamp: datetime = field(default_factory=datetime.utcnow)
    event_id: Optional[str] = None
    source: str = "capital_vortex"
    version: str = "1.0.0"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert event to Firestore-compatible dictionary."""
        data = asdict(self)
        data['timestamp'] = self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else self.timestamp
        data['event_type'] = self.event_type.value
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BaseEvent':
        """Create event from Firestore dictionary."""
        if 'timestamp' in data and isinstance(data['timestamp'], str):
            data['timestamp'] = datetime.fromisoformat(data['timestamp'].replace('Z', '+00:00'))
        data['event_type'] = EventType(data['event_type'])
        return cls(**data)


@dataclass
class MarketDataEvent(BaseEvent):
    """
    Market data from DEX feeds with triangulation validation.
    Stores OHLCV data with source verification.
    """
    symbol: str
    exchange: str
    price: float
    volume: float
    timestamp_exchange: datetime
    bid: Optional[float] = None
    ask: Optional[float] = None
    high_24h: Optional[float] = None
    low_24h: Optional[float] = None
    spread: Optional[float] = None
    sources_verified: int = 1  # Number of confirming sources
    
    def __post_init__(self):
        self.event_type = EventType.MARKET_DATA
        self.version = "1.1.0"
        
        # Calculate spread if not provided
        if self.spread is None and self.bid and self.ask:
            self.spread = self.ask - self.bid
    
    def is_valid(self) -> bool:
        """Validate market data for anomalies."""
        checks = [
            self.price > 0,
            self.volume >= 0,
            self.sources_verified >= 1,
            self.timestamp_exchange <= datetime.utcnow()
        ]
        return all(checks)


@dataclass
class MomentumSignalEvent(BaseEvent):
    """
    Trading signals generated by strategy modules.
    Includes confidence scores and validation metrics.
    """
    strategy_id: str
    symbol: str
    signal: float  # -1.0 to 1.0, where 1.0 is strong buy
    confidence: float  # 0.0 to 1.0
    target_price: Optional[float] = None
    stop_loss: Optional[float] = None
    time_horizon_minutes: int = 15
    indicators: Dict[str, float] = field(default_factory=dict)
    validation_score: float = 0.0
    
    def __post_init__(self):
        self.event_type = EventType.MOMENTUM_SIGNAL
        self.version = "1.0.0"
        
        # Clamp values
        self.signal = max(-1.0, min(1.0, self.signal))
        self.confidence = max(0.0, min(1.0, self.confidence))
        self.validation_score = max(0.0, min(1.0, self.validation_score))
    
    def get_action(self) -> str:
        """Convert signal to actionable trade decision."""
        if abs(self.signal) < 0.2:
            return "hold"
        elif self.signal > 0:
            return "buy" if self.signal > 0.5 else "weak_buy"
        else:
            return "sell" if self.signal < -0.5 else "weak_sell"


@dataclass
class TradeExecutionEvent(BaseEvent):
    """
    Record of completed trade execution with on-chain verification.
    Includes gas costs and MEV protection details.
    """
    execution_id: str
    strategy_id: str
    symbol: str
    side: str  # "buy" or "sell"
    quantity: float
    price_executed: float
    tx_hash: str
    gas_used: float
    gas_price_gwei: float
    block_number: int
    timestamp_block: datetime
    mev_protection: bool = False
    slippage_percent: float = 0.0
    status: str = "confirmed"  # pending, confirmed, reverted
    
    def __post_init__(self):
        self.event_type = EventType.TRADE_EXECUTION
        self.version = "1.0.0"
    
    def calculate_cost(self) -> Dict[str, float]:
        """Calculate total trade cost including gas."""
        trade_value = self.quantity * self.price_executed
        gas_cost_eth = (self.gas_used * self.gas_price_gwei) / 1e9
        
        return {
            'trade_value': trade_value,
            'gas_cost_eth': gas_cost_eth,
            'slippage_cost': trade_value * (self.slippage_percent / 100),
            'total_cost': trade_value + gas_cost_eth
        }


@dataclass
class ErrorEvent(BaseEvent):
    """
    System error events with severity classification.
    Used for monitoring and automatic recovery.
    """
    error_code: str
    error_message: str
    component: str
    severity: str  # "critical", "error", "warning", "info"
    stack_trace: Optional[str] = None
    recovery_action: Optional[str] = None
    data_context: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        self.event_type = EventType.ERROR_EVENT
        self.version = "1.0.0"


class EventValidator:
    """
    Validates events before storage to maintain data integrity.
    """
    
    @staticmethod
    def validate(event: BaseEvent) -> List[str]:
        """Validate event and return list of warnings/errors."""
        warnings = []
        
        # Type validation
        if not isinstance(event.timestamp, datetime):
            warnings.append("Invalid timestamp format")
        
        # Event-specific validation
        if isinstance(event, MarketDataEvent):
            if not event.is_valid():
                warnings.append("Invalid market data")
            if event.sources_verified < 2:
                warnings.append(f"Low source verification: {event.sources_verified}")
        
        elif isinstance(event, MomentumSignalEvent):
            if abs(event.signal) > 1.0:
                warnings.append(f"Signal out of bounds: {event.signal}")
            if event.confidence < 0.3 and abs(event.signal) > 0.5:
                warnings.append("High signal with low confidence")
        
        elif isinstance(event, TradeExecutionEvent):
            if event.slippage_percent > 5.0:
                warnings.append(f"High slippage: {event.slippage_percent}%")
            if event.gas_price_gwei > 100:
                warnings.append(f"High gas price: {event.gas_price_gwei} gwei")
        
        return warnings